# Generated by Django 6.1.2 on 2026-10-09 07:00

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense'), ('CASH', 'Cash'), ('BANK', 'Bank Account'), ('RECEIVABLE', 'Accounts Receivable'), ('PAYABLE', 'Accounts Payable'), ('COST_OF_GOODS', 'Cost of Goods Sold'), ('TAX', 'Tax')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_reconcilable', models.BooleanField(default=False)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('reference', models.CharField(db_index=True, max_length=50)),
                ('entry_type', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('INVOICE', 'Customer Invoice'), ('BILL', 'Supplier Bill'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('PAYROLL', 'Payroll'), ('DEPRECIATION', 'Depreciation'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('OPENING', 'Opening Balance'), ('CLOSING', 'Period Closing'), ('REVERSAL', 'Reversal')], default='MANUAL', max_length=20)),
                ('posting_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('source_document_type', models.CharField(blank=True, default='', max_length=50)),
                ('source_document_id', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-posting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('partner_id', models.CharField(blank=True, default='', max_length=50)),
                ('partner_type', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('is_inclusive', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
