# Generated by Django 6.1.2 on 2026-10-09 08:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('crm', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('default_useful_life', models.IntegerField(default=5)),
                ('default_depreciation_method', models.CharField(choices=[('SLM', 'Straight Line'), ('WDV', 'Written Down Value')], default='SLM', max_length=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='organizations.company')),
                ('gl_accumulated_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_category_accumulated_set', to='accounting.account')),
                ('gl_asset_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_category_asset_set', to='accounting.account')),
                ('gl_depreciation_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_category_depreciation_set', to='accounting.account')),
            ],
            options={
                'verbose_name_plural': 'asset categories',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('useful_life_years', models.IntegerField(default=5)),
                ('depreciation_method', models.CharField(choices=[('SLM', 'Straight Line'), ('WDV', 'Written Down Value')], default='SLM', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISPOSED', 'Disposed'), ('WRITTEN_OFF', 'Written Off'), ('UNDER_MAINTENANCE', 'Under Maintenance')], db_index=True, default='ACTIVE', max_length=20)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('book_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('last_depreciated', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='fixed_assets.assetcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='organizations.company')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.supplier')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('disposal_date', models.DateField()),
                ('disposal_type', models.CharField(choices=[('SALE', 'Sale'), ('SCRAP', 'Scrap'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('proceeds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('gain_loss', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='fixed_assets.fixedasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('period_date', models.DateField()),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('book_value_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciations', to='fixed_assets.fixedasset')),
            ],
            options={
                'ordering': ['-period_date'],
                'unique_together': {('asset', 'period_date')},
            },
        ),
    ]
