# Generated by Django 6.1.2 on 2026-10-09 07:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('hr', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('reference', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='organizations.company')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('paye_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('nssf_employee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('nhif_shif', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('housing_levy', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('component_type', models.CharField(choices=[('BASIC', 'Basic Salary'), ('ALLOWANCE', 'Allowance'), ('DEDUCTION', 'Deduction'), ('STATUTORY', 'Statutory Deduction'), ('OVERTIME', 'Overtime'), ('BONUS', 'Bonus')], max_length=15)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_fixed', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.company')),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
    ]
