# Generated by Django 6.1.2 on 2026-10-09 07:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('CURRENT', 'Current'), ('SAVINGS', 'Savings'), ('FIXED', 'Fixed Deposit'), ('PETTY_CASH', 'Petty Cash')], default='CURRENT', max_length=20)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('branch', models.CharField(blank=True, default='', max_length=200)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='organizations.company')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('transaction_date', models.DateField(db_index=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit / Inflow'), ('DEBIT', 'Debit / Outflow')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('is_reconciled', models.BooleanField(db_index=True, default=False)),
                ('running_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
